// apps/mail/app/(routes)/settings/connections/page.tsx
'use client';

import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { AddConnectionDialog } from '@/components/connection/add';
import { useSession, authClient } from '@/lib/auth-client';
import { useConnections } from '@/hooks/use-connections';
import { useTRPC } from '@/providers/query-provider';
import { Skeleton } from '@/components/ui/skeleton';
import { useMutation } from '@tanstack/react-query';
import { Trash, Plus, Unplug } from 'lucide-react';
import { useThreads } from '@/hooks/use-threads';
import { emailProviders } from '@/lib/constants';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';

function ConnectionSkeleton() {
  return (
    <div className="flex items-center gap-4 rounded-xl border p-4">
      <Skeleton className="h-10 w-10 rounded-full" />
      <div className="flex flex-1 flex-col gap-1.5">
        <Skeleton className="h-4 w-28 rounded" />
        <Skeleton className="h-3 w-44 rounded" />
      </div>
      <Skeleton className="h-8 w-8 rounded-full" />
    </div>
  );
}

export default function ConnectionsPage() {
  const { data, isPending, refetch: refetchConnections } = useConnections();
  const { refetch } = useSession();

  const trpc = useTRPC();
  const { mutateAsync: deleteConnection } = useMutation(trpc.connections.delete.mutationOptions());
  const [{ refetch: refetchThreads }] = useThreads();

  const disconnectAccount = async (connectionId: string) => {
    await deleteConnection(
      { connectionId },
      {
        onError: (error) => {
          console.error('Error disconnecting account:', error);
          toast.error('Failed to disconnect account');
        },
      },
    );
    toast.success('Account disconnected successfully');
    void refetchConnections();
    refetch();
    void refetchThreads();
  };

  const connections = data?.connections ?? [];
  const disconnectedIds = data?.disconnectedIds ?? [];

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-lg font-semibold">Email Accounts</h2>
          <p className="text-muted-foreground text-sm">
            Manage your connected email accounts. Add or remove accounts to access your mail.
          </p>
        </div>
      </div>

      {isPending ? (
        <div className="space-y-3">
          <ConnectionSkeleton />
          <ConnectionSkeleton />
        </div>
      ) : connections.length === 0 ? (
        <div className="flex flex-col items-center justify-center gap-3 rounded-xl border border-dashed py-12">
          <div className="bg-muted flex h-12 w-12 items-center justify-center rounded-full">
            <Plus className="text-muted-foreground h-6 w-6" />
          </div>
          <div className="text-center">
            <p className="text-sm font-medium">No accounts connected</p>
            <p className="text-muted-foreground text-sm">
              Connect an email account to get started.
            </p>
          </div>
          <AddConnectionDialog>
            <Button variant="outline" size="sm" className="mt-1">
              <Plus className="size-4" />
              Add Account
            </Button>
          </AddConnectionDialog>
        </div>
      ) : (
        <>
          <div className="space-y-3">
            {connections.map((connection) => {
              const provider = emailProviders.find((p) => p.providerId === connection.providerId);
              const Icon = provider?.icon;
              const isDisconnected = disconnectedIds.includes(connection.id);
              const isOnly = connections.length === 1;

              return (
                <div
                  key={connection.id}
                  className="flex items-center gap-4 rounded-xl border p-4 transition-colors hover:bg-black/2 dark:hover:bg-white/2"
                >
                  {connection.picture ? (
                    <img
                      src={connection.picture}
                      alt=""
                      className="h-10 w-10 shrink-0 rounded-full object-cover"
                      width={40}
                      height={40}
                    />
                  ) : (
                    <div className="bg-muted flex h-10 w-10 shrink-0 items-center justify-center rounded-full">
                      {Icon && <Icon className="size-5" />}
                    </div>
                  )}

                  <div className="flex min-w-0 flex-1 flex-col">
                    <div className="flex items-center gap-2">
                      <span className="truncate text-sm font-medium">{connection.name}</span>
                      {provider && (
                        <span className="text-muted-foreground text-xs">{provider.name}</span>
                      )}
                      {isDisconnected && <Badge variant="destructive">Disconnected</Badge>}
                    </div>
                    <span className="text-muted-foreground max-w-[280px] cursor-default truncate text-xs">
                      {connection.email}
                    </span>
                  </div>

                  <div className="flex shrink-0 items-center gap-2">
                    {isDisconnected && (
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={async () => {
                          await authClient.linkSocial({
                            provider: connection.providerId,
                            callbackURL: `${window.location.origin}/settings/connections`,
                          });
                        }}
                      >
                        <Unplug className="size-4" />
                        Reconnect
                      </Button>
                    )}
                    <Dialog>
                      <DialogTrigger
                        render={
                          <Button
                            variant="ghost"
                            size="icon"
                            className="text-muted-foreground hover:text-destructive h-8 w-8"
                            disabled={isOnly}
                          >
                            <Trash className="h-4 w-4" />
                          </Button>
                        }
                      />
                      <DialogContent>
                        <DialogHeader>
                          <DialogTitle>Disconnect Email Account</DialogTitle>
                          <DialogDescription>
                            Are you sure you want to disconnect{' '}
                            <span className="text-foreground font-medium">{connection.email}</span>?
                            You can reconnect it later.
                          </DialogDescription>
                        </DialogHeader>
                        <div className="flex justify-end gap-3">
                          <DialogClose render={<Button variant="outline">Cancel</Button>} />
                          <DialogClose
                            render={
                              <Button
                                variant="destructive"
                                onClick={() => disconnectAccount(connection.id)}
                              >
                                Disconnect
                              </Button>
                            }
                          />
                        </div>
                      </DialogContent>
                    </Dialog>
                  </div>
                </div>
              );
            })}
          </div>
          <AddConnectionDialog>
            <Button size="sm">
              <Plus className="size-4" />
              Add Account
            </Button>
          </AddConnectionDialog>
        </>
      )}
    </div>
  );
}

// apps/mail-new/pages/settings/connections.vue
<script setup lang="ts">
import { emailProviders } from '~/utils/constants';

definePageMeta({
  middleware: ['auth'],
});

const trpc = useTrpc();
const { linkSocial } = useAuth();
const { data, isPending, refreshConnections } = useConnections();

const selectedProvider = ref<string | null>(null);
const accountEmail = ref('');
const appPassword = ref('');
const errorMessage = ref('');
const successMessage = ref('');
const isSubmitting = ref(false);

await refreshConnections();

const connectProvider = async (providerId: string) => {
  errorMessage.value = '';
  successMessage.value = '';

  if (providerId === 'icloud' || providerId === 'yahoo') {
    selectedProvider.value = providerId;
    accountEmail.value = '';
    appPassword.value = '';
    return;
  }

  const callbackURL = `${window.location.origin}/settings/connections`;
  const result = await linkSocial(providerId, callbackURL);
  if (!result.ok) {
    errorMessage.value = result.error;
  }
};

const connectAppPasswordProvider = async () => {
  if (!selectedProvider.value) {
    return;
  }
  errorMessage.value = '';
  successMessage.value = '';
  isSubmitting.value = true;
  try {
    if (selectedProvider.value === 'icloud') {
      await trpc.connections.createIcloud.mutate({
        email: accountEmail.value,
        password: appPassword.value,
      });
    } else {
      await trpc.connections.createYahoo.mutate({
        email: accountEmail.value,
        password: appPassword.value,
      });
    }
    selectedProvider.value = null;
    successMessage.value = 'Account connected';
    await refreshConnections();
  } catch (error: any) {
    errorMessage.value = error?.message || 'Failed to connect account';
  } finally {
    isSubmitting.value = false;
  }
};

const disconnectAccount = async (connectionId: string) => {
  errorMessage.value = '';
  successMessage.value = '';
  try {
    await trpc.connections.delete.mutate({ connectionId });
    await refreshConnections();
    successMessage.value = 'Account disconnected';
  } catch (error: any) {
    errorMessage.value = error?.message || 'Failed to disconnect account';
  }
};
</script>

<template>
  <AppShell section="settings">
    <div class="mx-auto max-w-3xl space-y-6">
      <div>
        <h1 class="text-xl font-semibold text-white">Connections</h1>
        <p class="text-sm text-zinc-400">Manage your connected email accounts.</p>
      </div>

      <section v-if="selectedProvider" class="panel space-y-3 p-4">
        <h2 class="text-sm font-semibold text-white">
          Connect {{ selectedProvider === 'icloud' ? 'iCloud' : 'Yahoo' }} with app password
        </h2>
        <input v-model="accountEmail" type="email" placeholder="you@example.com" />
        <input v-model="appPassword" type="password" placeholder="App password" />
        <div class="flex gap-2">
          <button type="button" :disabled="isSubmitting" @click="connectAppPasswordProvider">
            {{ isSubmitting ? 'Connecting...' : 'Connect' }}
          </button>
          <button class="btn-secondary" type="button" @click="selectedProvider = null">Cancel</button>
        </div>
      </section>

      <section class="panel space-y-3 p-4">
        <h2 class="text-sm font-semibold text-white">Add account</h2>
        <div class="grid grid-cols-2 gap-2">
          <button
            v-for="provider in emailProviders"
            :key="provider.providerId"
            class="btn-secondary"
            type="button"
            @click="connectProvider(provider.providerId)"
          >
            {{ provider.name }}
          </button>
        </div>
      </section>

      <section class="panel p-4">
        <h2 class="mb-3 text-sm font-semibold text-white">Connected accounts</h2>
        <div v-if="isPending" class="text-sm text-zinc-500">Loading accounts...</div>
        <div v-else-if="!data?.connections?.length" class="text-sm text-zinc-500">
          No accounts connected.
        </div>
        <div v-else class="space-y-2">
          <div
            v-for="connection in data.connections"
            :key="connection.id"
            class="flex items-center justify-between rounded-md border border-zinc-800 p-3"
          >
            <div>
              <p class="text-sm text-zinc-200">{{ connection.name }}</p>
              <p class="text-xs text-zinc-500">{{ connection.email }}</p>
              <p
                v-if="data.disconnectedIds?.includes(connection.id)"
                class="mt-1 text-xs text-amber-400"
              >
                Disconnected
              </p>
            </div>
            <div class="flex gap-2">
              <button
                v-if="data.disconnectedIds?.includes(connection.id)"
                class="btn-secondary"
                type="button"
                @click="
                  connectProvider(connection.providerId)
                "
              >
                Reconnect
              </button>
              <button
                class="btn-secondary"
                type="button"
                :disabled="(data.connections?.length || 0) <= 1"
                @click="disconnectAccount(connection.id)"
              >
                Disconnect
              </button>
            </div>
          </div>
        </div>
      </section>

      <p v-if="successMessage" class="text-sm text-emerald-400">{{ successMessage }}</p>
      <p v-if="errorMessage" class="text-sm text-red-400">{{ errorMessage }}</p>
    </div>
  </AppShell>
</template>
