// apps/mail/app/(routes)/settings/general/page.tsx
'use client';

import { authClient, useSession } from '@/lib/auth-client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useState } from 'react';
import { toast } from 'sonner';

export default function GeneralSettingsPage() {
  const { data: session, isPending } = useSession();
  const [name, setName] = useState('');
  const [nameLoaded, setNameLoaded] = useState(false);
  const [isSavingName, setIsSavingName] = useState(false);

  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [isChangingPassword, setIsChangingPassword] = useState(false);

  if (!nameLoaded && session?.user?.name) {
    setName(session.user.name);
    setNameLoaded(true);
  }

  const handleUpdateName = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) {
      toast.error('Name cannot be empty');
      return;
    }

    setIsSavingName(true);
    try {
      await authClient.updateUser({ name: name.trim() });
      toast.success('Name updated');
    } catch {
      toast.error('Failed to update name');
    } finally {
      setIsSavingName(false);
    }
  };

  const handleChangePassword = async (e: React.FormEvent) => {
    e.preventDefault();

    if (newPassword.length < 8) {
      toast.error('New password must be at least 8 characters');
      return;
    }

    if (newPassword !== confirmPassword) {
      toast.error('Passwords do not match');
      return;
    }

    setIsChangingPassword(true);
    try {
      const result = await authClient.changePassword({
        currentPassword,
        newPassword,
        revokeOtherSessions: false,
      });

      if (result.error) {
        toast.error(result.error.message ?? 'Failed to change password');
        return;
      }

      toast.success('Password changed');
      setCurrentPassword('');
      setNewPassword('');
      setConfirmPassword('');
    } catch {
      toast.error('Failed to change password');
    } finally {
      setIsChangingPassword(false);
    }
  };

  if (isPending) return null;

  return (
    <div className="space-y-10">
      <div>
        <h2 className="text-lg font-semibold">General</h2>
        <p className="text-muted-foreground text-sm">Manage your account details.</p>
      </div>

      <div className="space-y-4">
        <div>
          <h3 className="text-sm font-medium">Email</h3>
          <p className="text-muted-foreground mt-1 text-sm">{session?.user?.email}</p>
        </div>

        <form onSubmit={handleUpdateName} className="space-y-3">
          <div className="space-y-2">
            <label htmlFor="name" className="text-sm font-medium">
              Name
            </label>
            <Input
              id="name"
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Your name"
              required
            />
          </div>
          <Button type="submit" size="sm" disabled={isSavingName}>
            {isSavingName ? 'Saving...' : 'Update Name'}
          </Button>
        </form>
      </div>

      <div className="border-t pt-8">
        <h3 className="text-sm font-medium">Change Password</h3>
        <p className="text-muted-foreground mb-4 text-sm">
          Update the password you use to log in.
        </p>

        <form onSubmit={handleChangePassword} className="space-y-3">
          <div className="space-y-2">
            <label htmlFor="current-password" className="text-sm font-medium">
              Current Password
            </label>
            <Input
              id="current-password"
              type="password"
              value={currentPassword}
              onChange={(e) => setCurrentPassword(e.target.value)}
              placeholder="Your current password"
              required
              autoComplete="current-password"
            />
          </div>
          <div className="space-y-2">
            <label htmlFor="new-password" className="text-sm font-medium">
              New Password
            </label>
            <Input
              id="new-password"
              type="password"
              value={newPassword}
              onChange={(e) => setNewPassword(e.target.value)}
              placeholder="Min. 8 characters"
              required
              minLength={8}
              autoComplete="new-password"
            />
          </div>
          <div className="space-y-2">
            <label htmlFor="confirm-password" className="text-sm font-medium">
              Confirm New Password
            </label>
            <Input
              id="confirm-password"
              type="password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              placeholder="Re-enter new password"
              required
              minLength={8}
              autoComplete="new-password"
            />
          </div>
          <Button type="submit" size="sm" disabled={isChangingPassword}>
            {isChangingPassword ? 'Changing...' : 'Change Password'}
          </Button>
        </form>
      </div>
    </div>
  );
}

// apps/mail-new/pages/settings/general.vue
<script setup lang="ts">
definePageMeta({
  middleware: ['auth'],
});

const trpc = useTrpc();
const { session, refreshSession, updateUserName, changePassword } = useAuth();

await refreshSession();

const name = ref(session.value?.user?.name || '');
const currentPassword = ref('');
const newPassword = ref('');
const confirmPassword = ref('');
const externalImages = ref(false);
const isSavingName = ref(false);
const isChangingPassword = ref(false);
const isSavingSettings = ref(false);
const errorMessage = ref('');
const successMessage = ref('');

const loadSettings = async () => {
  try {
    const result = await trpc.settings.get.query();
    externalImages.value = Boolean(result?.settings?.externalImages);
  } catch {
    externalImages.value = false;
  }
};

await loadSettings();

const saveName = async () => {
  if (!name.value.trim()) {
    errorMessage.value = 'Name cannot be empty';
    return;
  }
  errorMessage.value = '';
  successMessage.value = '';
  isSavingName.value = true;
  try {
    const result = await updateUserName(name.value.trim());
    if (!result.ok) {
      errorMessage.value = result.error;
      return;
    }
    successMessage.value = 'Name updated';
  } finally {
    isSavingName.value = false;
  }
};

const savePassword = async () => {
  errorMessage.value = '';
  successMessage.value = '';
  if (newPassword.value.length < 8) {
    errorMessage.value = 'New password must be at least 8 characters';
    return;
  }
  if (newPassword.value !== confirmPassword.value) {
    errorMessage.value = 'Passwords do not match';
    return;
  }
  isChangingPassword.value = true;
  try {
    const result = await changePassword(currentPassword.value, newPassword.value);
    if (!result.ok) {
      errorMessage.value = result.error;
      return;
    }
    successMessage.value = 'Password changed';
    currentPassword.value = '';
    newPassword.value = '';
    confirmPassword.value = '';
  } finally {
    isChangingPassword.value = false;
  }
};

const saveSettings = async () => {
  errorMessage.value = '';
  successMessage.value = '';
  isSavingSettings.value = true;
  try {
    await trpc.settings.save.mutate({
      externalImages: externalImages.value,
    });
    successMessage.value = 'Settings saved';
  } catch (error: any) {
    errorMessage.value = error?.message || 'Failed to save settings';
  } finally {
    isSavingSettings.value = false;
  }
};
</script>

<template>
  <AppShell section="settings">
    <div class="mx-auto max-w-2xl space-y-8">
      <div>
        <h1 class="text-xl font-semibold text-white">General</h1>
        <p class="text-sm text-zinc-400">Manage your account details.</p>
      </div>

      <section class="panel space-y-4 p-4">
        <h2 class="text-sm font-semibold text-white">Profile</h2>
        <div class="space-y-1">
          <p class="text-xs text-zinc-500">Email</p>
          <p class="text-sm text-zinc-200">{{ session?.user?.email }}</p>
        </div>
        <div class="space-y-1">
          <label class="text-sm text-zinc-300">Name</label>
          <input v-model="name" type="text" />
        </div>
        <button type="button" :disabled="isSavingName" @click="saveName">
          {{ isSavingName ? 'Saving...' : 'Update name' }}
        </button>
      </section>

      <section class="panel space-y-4 p-4">
        <h2 class="text-sm font-semibold text-white">Privacy</h2>
        <label class="flex items-center gap-2 text-sm text-zinc-300">
          <input v-model="externalImages" type="checkbox" class="h-4 w-4" />
          Load external images automatically
        </label>
        <button type="button" :disabled="isSavingSettings" @click="saveSettings">
          {{ isSavingSettings ? 'Saving...' : 'Save preferences' }}
        </button>
      </section>

      <section class="panel space-y-4 p-4">
        <h2 class="text-sm font-semibold text-white">Change Password</h2>
        <input v-model="currentPassword" type="password" placeholder="Current password" />
        <input v-model="newPassword" type="password" placeholder="New password" minlength="8" />
        <input
          v-model="confirmPassword"
          type="password"
          placeholder="Confirm new password"
          minlength="8"
        />
        <button type="button" :disabled="isChangingPassword" @click="savePassword">
          {{ isChangingPassword ? 'Changing...' : 'Change password' }}
        </button>
      </section>

      <p v-if="successMessage" class="text-sm text-emerald-400">{{ successMessage }}</p>
      <p v-if="errorMessage" class="text-sm text-red-400">{{ errorMessage }}</p>
    </div>
  </AppShell>
</template>
