// apps/mail/app/(auth)/onboarding/page.tsx
'use client';

import { authClient, useSession } from '@/lib/auth-client';
import { ICloudForm } from '@/components/connection/icloud-form';
import { YahooForm } from '@/components/connection/yahoo-form';
import { useConnections } from '@/hooks/use-connections';
import { emailProviders } from '@/lib/constants';
import { ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';

export default function OnboardingPage() {
  const router = useRouter();
  const { data: session, isPending } = useSession();
  const { data: connectionsData, refetch: refetchConnections } = useConnections();
  const [appPasswordProvider, setAppPasswordProvider] = useState<string | null>(null);

  const hasConnections = (connectionsData?.connections?.length ?? 0) > 0;

  useEffect(() => {
    if (!isPending && !session?.user) {
      router.push('/login');
    }
  }, [session, isPending, router]);

  const handleProviderClick = async (providerId: string) => {
    if (providerId === 'icloud' || providerId === 'yahoo') {
      setAppPasswordProvider(providerId);
      return;
    }
    await authClient.linkSocial({
      provider: providerId,
      callbackURL: `${window.location.origin}/mail/inbox`,
    });
  };

  const handleAppPasswordSuccess = async () => {
    setAppPasswordProvider(null);
    await refetchConnections();
  };

  if (isPending) return null;

  return (
    <div className="flex min-h-screen w-full flex-col items-center justify-center bg-[#111111] px-4">
      <div className="w-full max-w-md space-y-8">
        <div className="text-center">
          <h1 className="text-2xl font-semibold text-white">Connect your email</h1>
          <p className="mt-2 text-sm text-white/60">
            {hasConnections
              ? 'Your account is connected. Add more or head to your inbox.'
              : 'Connect an email account to start using your inbox.'}
          </p>
        </div>

        {appPasswordProvider === 'icloud' ? (
          <div className="rounded-xl border border-white/10 bg-white/5 p-6">
            <ICloudForm
              defaultEmail=""
              onSuccess={handleAppPasswordSuccess}
              onBack={() => setAppPasswordProvider(null)}
            />
          </div>
        ) : appPasswordProvider === 'yahoo' ? (
          <div className="rounded-xl border border-white/10 bg-white/5 p-6">
            <YahooForm
              defaultEmail=""
              onSuccess={handleAppPasswordSuccess}
              onBack={() => setAppPasswordProvider(null)}
            />
          </div>
        ) : (
          <div className="grid grid-cols-2 gap-4">
            {emailProviders.map((provider) => {
              const Icon = provider.icon;
              return (
                <Button
                  key={provider.providerId}
                  variant="secondary"
                  className="h-24 w-full flex-col items-center justify-center gap-2"
                  onClick={() => handleProviderClick(provider.providerId)}
                >
                  <Icon className="size-6!" />
                  <span className="text-xs">{provider.name}</span>
                </Button>
              );
            })}
          </div>
        )}

        {hasConnections && (
          <Button
            className="w-full"
            onClick={() => {
              window.location.href = '/mail/inbox';
            }}
          >
            Go to Inbox
            <ArrowRight className="ml-2 size-4" />
          </Button>
        )}
      </div>
    </div>
  );
}

// apps/mail-new/pages/onboarding.vue
<script setup lang="ts">
import { emailProviders } from '~/utils/constants';

definePageMeta({
  middleware: ['auth'],
});

const { linkSocial } = useAuth();
const trpc = useTrpc();
const { data, refreshConnections } = useConnections();

const selectedProvider = ref<string | null>(null);
const accountEmail = ref('');
const appPassword = ref('');
const isSubmitting = ref(false);
const errorMessage = ref('');

await refreshConnections();

const hasConnections = computed(() => (data.value?.connections?.length ?? 0) > 0);

const pickProvider = async (providerId: string) => {
  errorMessage.value = '';
  if (providerId === 'icloud' || providerId === 'yahoo') {
    selectedProvider.value = providerId;
    accountEmail.value = '';
    appPassword.value = '';
    return;
  }

  const callbackURL = `${window.location.origin}/mail/inbox`;
  const result = await linkSocial(providerId, callbackURL);
  if (!result.ok) {
    errorMessage.value = result.error;
  }
};

const saveAppPasswordConnection = async () => {
  if (!selectedProvider.value) {
    return;
  }

  isSubmitting.value = true;
  errorMessage.value = '';
  try {
    if (selectedProvider.value === 'icloud') {
      await trpc.connections.createIcloud.mutate({
        email: accountEmail.value,
        password: appPassword.value,
      });
    } else {
      await trpc.connections.createYahoo.mutate({
        email: accountEmail.value,
        password: appPassword.value,
      });
    }
    selectedProvider.value = null;
    accountEmail.value = '';
    appPassword.value = '';
    await refreshConnections();
  } catch (error: any) {
    errorMessage.value = error?.message || 'Failed to connect account';
  } finally {
    isSubmitting.value = false;
  }
};
</script>

<template>
  <div class="flex min-h-screen items-center justify-center px-4">
    <div class="w-full max-w-xl space-y-6">
      <div class="space-y-2 text-center">
        <h1 class="text-2xl font-semibold text-white">Connect your email</h1>
        <p class="text-sm text-zinc-400">
          {{
            hasConnections
              ? 'Your account is connected. Add more or head to your inbox.'
              : 'Connect an email account to start using your inbox.'
          }}
        </p>
      </div>

      <div v-if="selectedProvider" class="panel space-y-3 p-4">
        <h2 class="text-sm font-semibold text-white">
          Connect {{ selectedProvider === 'icloud' ? 'iCloud' : 'Yahoo' }} with app password
        </h2>
        <input v-model="accountEmail" type="email" placeholder="you@example.com" />
        <input v-model="appPassword" type="password" placeholder="App password" />
        <div class="flex gap-2">
          <button type="button" :disabled="isSubmitting" @click="saveAppPasswordConnection">
            {{ isSubmitting ? 'Connecting...' : 'Connect' }}
          </button>
          <button class="btn-secondary" type="button" @click="selectedProvider = null">
            Back
          </button>
        </div>
      </div>

      <div v-else class="grid grid-cols-2 gap-3">
        <button
          v-for="provider in emailProviders"
          :key="provider.providerId"
          class="btn-secondary h-20"
          type="button"
          @click="pickProvider(provider.providerId)"
        >
          {{ provider.name }}
        </button>
      </div>

      <p v-if="errorMessage" class="text-sm text-red-400">{{ errorMessage }}</p>

      <button v-if="hasConnections" class="w-full" type="button" @click="navigateTo('/mail/inbox')">
        Go to Inbox
      </button>
    </div>
  </div>
</template>
