// apps/mail-new/pages/signup.vue
<script setup lang="ts">
definePageMeta({
  middleware: ['guest'],
});

const { signUpEmail } = useAuth();

const name = ref('');
const email = ref('');
const password = ref('');
const isLoading = ref(false);
const errorMessage = ref('');

const submitSignup = async () => {
  errorMessage.value = '';
  if (password.value.length < 8) {
    errorMessage.value = 'Password must be at least 8 characters';
    return;
  }

  isLoading.value = true;
  try {
    const result = await signUpEmail(name.value, email.value, password.value);
    if (!result.ok) {
      errorMessage.value = result.error;
      return;
    }
    await navigateTo('/mail/inbox');
  } finally {
    isLoading.value = false;
  }
};
</script>

<template>
  <div class="flex min-h-screen items-center justify-center px-4">
    <div class="w-full max-w-sm space-y-6">
      <div class="space-y-2 text-center">
        <h1 class="text-2xl font-semibold text-white">Create your account</h1>
        <p class="text-sm text-zinc-400">Sign up to get started with your email.</p>
      </div>
      <form class="space-y-3" @submit.prevent="submitSignup">
        <div class="space-y-1">
          <label class="text-sm text-zinc-300" for="name">Name</label>
          <input id="name" v-model="name" type="text" required />
        </div>
        <div class="space-y-1">
          <label class="text-sm text-zinc-300" for="email">Email</label>
          <input id="email" v-model="email" type="email" required />
        </div>
        <div class="space-y-1">
          <label class="text-sm text-zinc-300" for="password">Password</label>
          <input id="password" v-model="password" type="password" minlength="8" required />
        </div>
        <button class="w-full" type="submit" :disabled="isLoading">
          {{ isLoading ? 'Creating account...' : 'Create account' }}
        </button>
      </form>
      <p v-if="errorMessage" class="text-sm text-red-400">{{ errorMessage }}</p>
      <p class="text-center text-sm text-zinc-400">
        Already have an account?
        <NuxtLink to="/login" class="text-zinc-200 underline">Log in</NuxtLink>
      </p>
    </div>
  </div>
</template>

// apps/mail/app/(auth)/signup/page.tsx
'use client';

import { signUp } from '@/lib/auth-client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { toast } from 'sonner';
import Link from 'next/link';

export default function SignupPage() {
  const router = useRouter();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (password.length < 8) {
      toast.error('Password must be at least 8 characters');
      return;
    }

    setIsLoading(true);
    try {
      const result = await signUp.email({
        name,
        email,
        password,
      });

      if (result.error) {
        toast.error(result.error.message ?? 'Failed to create account');
        return;
      }

      router.push('/mail');
    } catch {
      toast.error('Something went wrong. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen w-full flex-col items-center justify-center bg-[#111111] px-4">
      <div className="w-full max-w-sm space-y-8">
        <div className="text-center">
          <h1 className="text-2xl font-semibold text-white">Create your account</h1>
          <p className="mt-2 text-sm text-white/60">
            Sign up to get started with your email.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <label htmlFor="name" className="text-sm font-medium text-white/80">
              Name
            </label>
            <Input
              id="name"
              type="text"
              placeholder="Your name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
              disabled={isLoading}
              className="border-white/10 bg-white/5 text-white placeholder:text-white/30"
            />
          </div>

          <div className="space-y-2">
            <label htmlFor="email" className="text-sm font-medium text-white/80">
              Email
            </label>
            <Input
              id="email"
              type="email"
              placeholder="you@example.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              disabled={isLoading}
              className="border-white/10 bg-white/5 text-white placeholder:text-white/30"
            />
          </div>

          <div className="space-y-2">
            <label htmlFor="password" className="text-sm font-medium text-white/80">
              Password
            </label>
            <Input
              id="password"
              type="password"
              placeholder="Min. 8 characters"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              minLength={8}
              disabled={isLoading}
              className="border-white/10 bg-white/5 text-white placeholder:text-white/30"
            />
          </div>

          <Button type="submit" className="w-full" disabled={isLoading}>
            {isLoading ? 'Creating account...' : 'Create account'}
          </Button>
        </form>

        <p className="text-center text-sm text-white/40">
          Already have an account?{' '}
          <Link href="/login" className="text-white/70 underline hover:text-white">
            Log in
          </Link>
        </p>
      </div>
    </div>
  );
}
